const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync(require('node:path').join(__dirname, 'index.html'), 'utf8');
new vm.Script(html.match(/<script>([\s\S]*?)<\/script>/)[1]);
const names = ['parseLayout', 'parseYT', 'liveCorrection', 'planSideTile', 'resizeBoundary'];
const code = names.map(name => html.match(new RegExp('function ' + name + '\\([^]*?^}', 'm'))[0]).join('\n');
const api = vm.runInNewContext(code + '\n({' + names.join(',') + '})', { URL });
const json = value => JSON.stringify(value);
const close = (actual, expected) => assert.ok(Math.abs(actual - expected) < 1e-9, `${actual} != ${expected}`);

for (const url of ['HPZKOGy7bAA', 'https://www.youtube.com/watch?v=HPZKOGy7bAA', 'https://youtu.be/HPZKOGy7bAA', 'https://www.youtube.com/live/HPZKOGy7bAA'])
  assert.equal(api.parseYT(url).vid, 'HPZKOGy7bAA');
const channel = 'UC' + 'a'.repeat(22);
assert.equal(api.parseYT(channel).channel, channel);
assert.equal(api.parseYT('https://www.youtube.com/channel/' + channel + '/live').channel, channel);
for (const url of ['javascript:alert(1)', 'https://youtube.com.evil/watch?v=HPZKOGy7bAA', 'https://user:pass@youtube.com/watch?v=HPZKOGy7bAA', 'bad-video'])
  assert.equal(api.parseYT(url), null);

const sample = (liveEdge, time, state = 1, videoId = 'live') => ({ liveEdge, isLive: videoId === 'live', atLiveHead: false, time, state, videoId });
let live = api.liveCorrection(null, sample(100, 90), 60000, true);
assert.equal(live.reload, false);
live = api.liveCorrection(live, sample(110, 75), 70000, true);
assert.equal(live.live, true);
assert.equal(live.reload, true);
const cooling = api.liveCorrection(live, sample(120, 80), 80000, true);
assert.equal(cooling.reload, false);
const paused = api.liveCorrection(cooling, sample(160, 80, 2), 120000, true);
assert.equal(paused.reload, false);
assert.equal(api.liveCorrection(paused, sample(170, 80), 130000, true).reload, true);
assert.equal(api.liveCorrection(paused, sample(170, 80), 130000, false).reload, false);
assert.equal(api.liveCorrection(live, sample(200, 0, 1, 'new-video'), 140000, true).reload, false);
assert.equal(api.liveCorrection(live, { ...sample(200, 0, 1, 'new-video'), isLive: true }, 71000, true).reload, true);
let vod = api.liveCorrection(null, sample(300, 10, 1, 'vod'), 60000, true);
assert.equal(api.liveCorrection(vod, sample(300, 20, 1, 'vod'), 70000, true).reload, false);
assert.equal(api.liveCorrection(vod, sample(50000, 20, 1, 'vod'), 70000, true).live, false);
assert.equal(api.liveCorrection(live, sample(NaN, 0), 140000, true).reload, false);
assert.equal(api.liveCorrection(null, { ...sample(100, 60), isLive: true }, 60000, true).reload, true);
assert.equal(api.liveCorrection(live, { ...sample(200, 0), isLive: false }, 140000, true).reload, false);
assert.equal(api.liveCorrection(null, { ...sample(100, 60, 2), isLive: true }, 60000, true).reload, false);
assert.equal(api.liveCorrection(null, { ...sample(1000, 60), liveEdge: 70, atLiveHead: true, isLive: true }, 60000, true).reload, false);
assert.equal(api.liveCorrection(null, { ...sample(1000, 60), liveEdge: undefined, isLive: true }, 60000, true).reload, false);
assert.equal(api.liveCorrection(null, { ...sample(1000, 60), liveEdge: 90, isLive: true }, 60000, true).reload, true);
assert.equal(api.liveCorrection(null, { ...sample(100, 60), isLive: undefined }, 60000, true).reload, false);

const layout = JSON.parse(html.match(/const DEFAULT_LAYOUT = ("[^"]*")/)[1]);
assert.equal(layout, 'AABC\nAADE\nFGHI');
assert.ok(!/type: "(?:chat|x)"/.test(html.match(/const DEFAULT_TILES = \{[^]*?\n\};/)[0]));
const boxes = api.parseLayout(layout).boxes;
const rects = Object.fromEntries(Object.entries(boxes).map(([id, b]) => [id, { x0: b.c0 / 4, x1: (b.c1 + 1) / 4, y0: b.r0 / 3, y1: (b.r1 + 1) / 3 }]));
rects.A.y1 = 0.72;
const old = json(rects);
const added = api.planSideTile(layout, rects, [1, 1, 1, 1], 'J', 'A');
assert.equal(added.layout, 'AABCJ\nAADEJ\nFGHI.');
assert.equal(added.rects.J.y1, 0.72);
close(added.rects.B.x0, rects.B.x0 * 0.82);
assert.equal(added.cols.length, 5);
assert.equal(json(rects), old);
assert.equal(api.planSideTile(layout, rects, [1, 1, 1, 1], 'J', '').layout, 'AABCJ\nAADEJ\nFGHIJ');
assert.throws(() => api.planSideTile(layout, rects, [1, 1, 1, 1], 'A', 'A'));

const square = { A: { x0: 0, x1: .5, y0: 0, y1: .5 }, B: { x0: .5, x1: 1, y0: 0, y1: .5 }, C: { x0: 0, x1: .5, y0: .5, y1: 1 }, D: { x0: .5, x1: 1, y0: .5, y1: 1 } };
let boundary = api.resizeBoundary(square, 'A', 'x', 1000);
assert.equal(json(boundary.before), '["A"]');
assert.equal(json(boundary.after), '["B"]');
const tall = { A: { x0: 0, x1: .8, y0: 0, y1: .5 }, B: { x0: 0, x1: .8, y0: .5, y1: 1 }, J: { x0: .8, x1: 1, y0: 0, y1: 1 } };
boundary = api.resizeBoundary(tall, 'A', 'x', 1000);
assert.equal(json([...boundary.before].sort()), '["A","B"]');
assert.equal(json(boundary.after), '["J"]');
for (const id of boundary.before) tall[id].x1 = .7;
for (const id of boundary.after) tall[id].x0 = .7;
assert.equal(tall.B.x1, tall.J.x0);
const blank = { J: { x0: .8, x1: 1, y0: 0, y1: .7 } };
assert.equal(api.resizeBoundary(blank, 'J', 'y', 1000).max, 1);
blank.K = { x0: .8, x1: 1, y0: .8, y1: 1 };
assert.equal(api.resizeBoundary(blank, 'J', 'y', 1000).max, .8);
boundary = api.resizeBoundary(square, 'A', 'x', 100);
assert.equal(boundary.min, boundary.max);
console.log('OK: URL validation, live correction, optional panes, adjacent and blank-space resizing');
